// packages/web/src/components/NewChat/NewChat.tsx
import React, { useState, useEffect } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, Input, Form } from 'antd';
import { SendOutlined } from '@ant-design/icons';
import { useAssistantStore } from '@/stores/assistant';
import { useAuthStore } from '@/stores/auth';
import eventBus from '@/plugins/eventBus';
import { UPDATE_CHAT_LIST } from '@/helpers/HelperConstants';

const { TextArea } = Input;

interface CreateChatResponse {
  technical_id: string;
  initialMessage?: string;
}

interface NewChatProps {
  onCreated: (data: CreateChatResponse) => void;
}

const NewChat: React.FC<NewChatProps> = ({ onCreated }) => {
  const { t } = useTranslation();
  const [form] = Form.useForm();
  const [isLoading, setIsLoading] = useState(false);
  const assistantStore = useAssistantStore();
  const authStore = useAuthStore();
  const year = new Date().getFullYear();

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.has('name')) {
      const name = params.get('name');
      form.setFieldsValue({ name });
      handleSubmit({ name, description: '' });
      const url = new URL(window.location.href);
      url.searchParams.delete('name');
      window.history.replaceState({}, '', url);
    }
  }, [form]);

  const handleSubmit = async (values: { name: string; description: string }) => {
    setIsLoading(true);
    const initialMessage = values.name;
    const tempId = `temp-${Date.now()}`;
    onCreated({ technical_id: tempId, initialMessage });

    try {
      const chatName = values.name.substring(0, 50) + (values.name.length > 50 ? '...' : '');
      const { data } = await assistantStore.postChats({
        name: chatName,
        description: values.description || ''
      } as any);

      if (!(authStore as any).isLoggedIn) {
        assistantStore.setGuestChatsExist(true);
      }

      onCreated({
        technical_id: data.technical_id,
        initialMessage
      });
      eventBus.$emit(UPDATE_CHAT_LIST);
    } catch (error) {
      console.error('Error creating chat:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const getClickableExamples = () => {
    try {
      const examples = t('examples.items.clickable', { returnObjects: true });
      return Array.isArray(examples) ? examples : [];
    } catch {
      return [];
    }
  };

  const clickableExamples = getClickableExamples();

  return (
    <div className="new-chat bg-white min-h-full">
      <div className="new-chat__content max-w-2xl mx-auto px-6 py-12">
        <div className="mb-8">
          <h1 className="text-2xl font-semibold text-slate-900 mb-2">{t('new_chat.h1')}</h1>
          <p className="text-sm text-slate-600 leading-relaxed">{t('new_chat.h2')}</p>
          <p className="text-xs text-slate-500 mt-1">{t('new_chat.title')}</p>
        </div>

        <Form
          form={form}
          onFinish={handleSubmit}
          className="new-chat__form mb-6"
        >
          <Form.Item
            name="name"
            rules={[{ required: true, message: 'Please enter your request' }]}
          >
            <TextArea
              placeholder={t('new_chat.input.placeholder')}
              autoSize={{ minRows: 3, maxRows: 6 }}
              className="new-chat__textarea rounded-lg border-slate-200"
            />
          </Form.Item>

          <Form.Item>
            <Button
              type="primary"
              htmlType="submit"
              loading={isLoading}
              icon={<SendOutlined />}
              className="new-chat__submit-btn bg-blue-600 hover:bg-blue-700 border-blue-600"
            >
              Send
            </Button>
          </Form.Item>
        </Form>

        {clickableExamples.length > 0 && (
          <div className="new-chat__examples">
            <p className="text-xs font-medium text-slate-400 uppercase tracking-wider mb-3">{t('examples.title')}</p>
            <div className="flex flex-wrap gap-2 mb-4">
              {clickableExamples.map((example, index) => (
                <button
                  key={index}
                  type="button"
                  className="text-sm px-3 py-1.5 bg-white border border-slate-200 rounded-full text-slate-600 hover:bg-slate-50 hover:border-slate-300 hover:text-slate-900 transition-colors"
                  onClick={() => {
                    form.setFieldsValue({ name: example });
                    handleSubmit({ name: example, description: '' });
                  }}
                >
                  {example}
                </button>
              ))}
            </div>
            <p className="new-chat__examples-more text-xs text-slate-400 mt-2">
              {t('examples.items.readonly')}
            </p>
          </div>
        )}
      </div>

      <div className="new-chat__footer border-t border-slate-200 px-6 py-4">
        <p className="text-xs text-slate-400">
          Copyright © {year}{' '}
          <a target="_blank" href="https://www.cyoda.com/" rel="noopener noreferrer" className="hover:text-slate-600 transition-colors">
            CYODA Ltd.
          </a>
        </p>
      </div>
    </div>
  );
};

export default NewChat;

// packages/web/src/components/NewChat/NewChat.vue
<template>
  <div class="new-chat">
    <h1 class="new-chat-h1">{{ t('new_chat.h1') }}</h1>
    <h2>{{ t('new_chat.h2') }}</h2>
    <div class="new-chat__title">
      <img class="only-theme-light" src="@/assets/images/logo.gif"/>
      <img class="only-theme-dark" src="@/assets/images/logo-dark.gif"/>
      {{ t('new_chat.title') }}
    </div>

    <div class="new-chat__form" :class="{
      'is-loading': isLoading
    }">
      <el-input
          v-model="form.name"
          :disabled="isLoading"
          type="textarea"
          resize="none"
          :autosize="{ minRows: 1, maxRows: 10 }"
          :placeholder="t('new_chat.input.placeholder')"
      />
      <el-button :loading="isLoading" class="btn btn-primary btn-icon"
                 @click.prevent="onClickSend">
        <SendIcon/>
      </el-button>
    </div>

    <div class="new-chat__examples">
      <div class="new-chat__examples-title">{{ t('examples.title') }}</div>
      <div class="new-chat__buttons">
        <el-button
            v-for="example in examples"
            @click="onClickExample(example)"
            :class="{
            'readonly': example.readonly
          }"
        >
          {{ example.text }}
        </el-button>
      </div>
    </div>
    <div class="new-chat__footer">
      By using this service, you confirm that you have read and agree to our<br/>
      <a target="_blank" href="https://www.cyoda.com/terms-of-service">
        Terms & Conditions
      </a>
      and
      <a target="_blank" href="https://www.cyoda.com/privacy-policy">
        Privacy Policy
      </a>

      <p>Copyright © {{ year }} <a target="_blank" href="https://www.cyoda.com/">CYODA Ltd.</a></p>
    </div>
  </div>
</template>
<script setup lang="ts">
import SendIcon from '@/assets/images/icons/send.svg';

import {computed, ref} from "vue";
import eventBus from "@/plugins/eventBus";
import {UPDATE_CHAT_LIST} from "@/helpers/HelperConstants";
import useAssistantStore from "@/stores/assistant";
import type {CreateChatResponse} from "@/types/chat.d";
import {useI18n} from "vue-i18n";
import useAuthStore from "@/stores/auth";

const assistantStore = useAssistantStore();
const form = ref({
  name: '',
  description: '',
});

const emit = defineEmits<{
  created: [value: CreateChatResponse]
}>()

const isLoading = ref(false);
const {t, tm} = useI18n();

const examples = computed(() => {
  const items = tm('examples.items.clickable').map(el => {
    return {
      text: el,
    }
  });

  if (t('examples.items.readonly') !== 'examples.items.readonly') {
    items.push(
        {
          text: t('examples.items.readonly'),
          readonly: true,
        }
    )
  }
  return items;
});

const year = computed(() => {
  return new Date().getFullYear();
});

function onClickExample(example) {
  if (example.readonly) return;

  form.value.name = example.text;
}

async function onClickSend() {
  isLoading.value = true;
  try {
    const {data} = await assistantStore.postChats(form.value);
    const authStore = useAuthStore();
    if (!authStore.isLoggedIn) {
      assistantStore.setGuestChatsExist(true);
    }
    emit('created', data);
    eventBus.$emit(UPDATE_CHAT_LIST);
  } finally {
    isLoading.value = false;
  }
}
</script>

<style lang="scss">
@use '@/assets/css/particular/breakpoints';

.new-chat {
  max-width: 800px;
  margin: 0 auto;

  h1 {
    color: var(--color-title);
    margin: 0;
    font-size: 28px;
    text-align: center;
    font-weight: 600;
    letter-spacing: 2px;
  }

  h2 {
    color: var(--color-sub-title);
    font-size: 24px;
    font-weight: 400;
    text-align: center;
    margin: 12px 0;
  }

  &__title {
    color: var(--color-sub-title);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 40px;
    font-weight: 400;
    margin: 24px 0;
    flex-wrap: wrap;

    @include breakpoints.respond-max('sm') {
      font-size: 30px;
      text-align: center;
    }

    img {
      width: 120px;
      margin-right: 10px;
    }
  }

  &__form {
    display: flex;
    align-items: center;
    padding: 16px;
    border: 1px solid var(--input-border);
    border-radius: 10px;
    background: var(--input);

    &.is-loading {
      background-color: var(--input-disabled);
    }

    .el-textarea__inner {
      box-shadow: none !important;
      padding: 9px 10px 9px 0;
      font-size: 16px;
    }

    .btn-icon {
      border-radius: 4px;
      display: flex;
      align-items: center;
      justify-content: center;
      cursor: pointer;
      align-self: end;
      margin-bottom: 4px;
      margin-left: 16px;

      svg {
        fill: #fff;
      }
    }
  }

  .new-chat__examples-title {
    padding: 23px 0;
    text-align: center;
    font-size: 16px;
    font-weight: 400;
    color: var(--color-white-examples);
  }

  &__buttons {
    display: flex;
    justify-content: center;
    flex-wrap: wrap;
    gap: 12px;
    padding-bottom: 12px;

    .el-button + .el-button {
      margin: 0;
    }

    .el-button {
      outline: none !important;
      border-color: var(--bg-new-chat-button);
      background: var(--bg-new-chat-button);
      font-size: 16px;
      font-weight: 400;
      border-radius: 4px;
      transition: all 0.3s;

      &:hover {
        background: var(--bg-new-chat-button-hover);
        border-color: var(--bg-new-chat-button-hover);
      }

      &.readonly {
        background: var(--bg-new-chat-button-readonly);
        border-color: var(--bg-new-chat-button-readonly);
        cursor: default;

        &:hover {
          background: var(--bg-new-chat-button-readonly);
          border-color: var(--bg-new-chat-button-readonly);
        }
      }

      @include breakpoints.respond-max('sm') {
        white-space: wrap;
        height: auto;
      }
    }
  }

  &__footer {
    margin-top: 20px;
    font-size: 12px;
    text-align: center;
  }
}
</style>
