// packages/web/src/components/EntitiesDetailsDialog/EntitiesDetailsDialog.tsx
import React, { useMemo } from 'react';
import { Modal, Tabs, Button, Descriptions, Table, Divider } from 'antd';
import { RollbackOutlined } from '@ant-design/icons';

interface EntitiesDetailsDialogProps {
  visible: boolean;
  onClose: () => void;
  chatData: any;
  isLoadingRollback?: boolean;
  onRollbackChat?: () => void;
}

const EntitiesDetailsDialog: React.FC<EntitiesDetailsDialogProps> = ({
  visible,
  onClose,
  chatData,
  isLoadingRollback = false,
  onRollbackChat
}) => {
  const entitiesData = useMemo(() => {
    return chatData?.chat_body?.entities_data || {};
  }, [chatData]);

  const workflows = useMemo(() => {
    return Object.keys(entitiesData).map(id => ({
      id,
      ...entitiesData[id]
    }));
  }, [entitiesData]);

  const handleRollbackChat = () => {
    if (onRollbackChat) {
      onRollbackChat();
    }
  };

  const renderWorkflowDetails = (workflow: any) => {
    const columns = [
      {
        title: '#',
        dataIndex: 'index',
        key: 'index',
        width: 50,
        render: (_: any, __: any, index: number) => index + 1
      },
      {
        title: 'Date',
        dataIndex: 'date',
        key: 'date',
        width: 250
      },
      {
        title: 'Name',
        dataIndex: 'state',
        key: 'state'
      }
    ];

    return (
      <div className="entities-details-dialog-details">
        <Descriptions
          column={1}
          size="small"
          bordered
        >
          <Descriptions.Item label="ID" labelStyle={{ width: '300px' }}>
            {workflow.id}
          </Descriptions.Item>
          {workflow.next_transitions && workflow.next_transitions.length > 0 && (
            <Descriptions.Item label="Next Transitions">
              {workflow.next_transitions.join(', ')}
            </Descriptions.Item>
          )}
        </Descriptions>

        {workflow.entity_versions && workflow.entity_versions.length > 0 && (
          <div className="entities-details-dialog-details__entity-versions" style={{ marginTop: '16px' }}>
            <h3>Entity Versions</h3>
            <Table
              dataSource={workflow.entity_versions}
              columns={columns}
              pagination={false}
              scroll={{ y: 400 }}
              size="small"
              rowKey={(record, index) => `${workflow.id}-${index}`}
            />
          </div>
        )}
      </div>
    );
  };

  const tabItems = workflows.map(workflow => ({
    key: workflow.id,
    label: workflow.workflow_name || workflow.id,
    children: renderWorkflowDetails(workflow)
  }));

  return (
    <Modal
      title={
        <div style={{ display: 'flex', alignItems: 'center' }}>
          <span>Entities Data</span>
          <Divider type="vertical" />
          <Button
            onClick={handleRollbackChat}
            loading={isLoadingRollback}
            size="small"
            type="primary"
            icon={<RollbackOutlined />}
          >
            Restart workflows
          </Button>
        </div>
      }
      open={visible}
      onCancel={onClose}
      width="70%"
      footer={[
        <Button key="close" onClick={onClose}>
          Close
        </Button>
      ]}
      maskClosable={false}
    >
      {workflows.length > 0 ? (
        <Tabs items={tabItems} />
      ) : (
        <div>No entities data available</div>
      )}
    </Modal>
  );
};

export default EntitiesDetailsDialog;

// packages/ui-backup/src/components/EntitiesDetailsDialog/EntitiesDetailsDialog.vue
<template>
  <el-dialog
      v-model="dialogVisible"
      width="70%"
      :close-on-click-modal="false"
  >
    <template #header="{ close, titleId, titleClass }">
      <div class="my-header">
        <h4 :id="titleId" :class="titleClass">
          Entities Data
          <el-divider direction="vertical" />
          <el-button
              @click="onClickRollbackChat"
              :loading="isLoadingRollback"
              size="small"
              class="btn btn-primary"
          >
            Restart workflows
            <RollbackQuestionIcon class="icon"/>
          </el-button>
        </h4>
      </div>
    </template>
    <el-tabs>
      <el-tab-pane v-for="workflow in workflows" :label="workflow.workflow_name">
        <EntitiesDetailsDialogDetails :workflow="workflow"/>
      </el-tab-pane>
    </el-tabs>
    <template #footer>
      <div class="dialog-footer">
        <el-button @click="dialogVisible = false">Close</el-button>
      </div>
    </template>
  </el-dialog>
</template>

<script setup lang="ts">
import {inject, computed, ref} from "vue";
import EntitiesDetailsDialogDetails from "@/components/EntitiesDetailsDialog/EntitiesDetailsDialogDetails.vue";
import RollbackQuestionIcon from "@/assets/images/icons/rollback-question.svg";
import eventBus from "@/plugins/eventBus";
import {ROLLBACK_CHAT} from "@/helpers/HelperConstants";

const dialogVisible = defineModel();
const chatData = inject('chatData');
const isLoadingRollback = inject('isLoadingRollback');

function onClickRollbackChat() {
  eventBus.$emit(ROLLBACK_CHAT);
}

const entitiesData = computed(() => {
  return chatData.value?.chat_body?.entities_data || {};
})

const workflows = computed(() => {
  return Object.keys(entitiesData.value).map(id => {
    return {
      id,
      ...entitiesData.value[id]
    }
  })
})

</script>

<style scoped lang="scss">
.icon{
  margin-left: 5px;
  position: relative;
  top: 2px;
}
</style>
