// packages/web/src/components/Editor/Editor.tsx
import React, { useRef, useEffect, useImperativeHandle, forwardRef } from 'react';
import * as monaco from 'monaco-editor';
import type { EditorAction } from '@/utils/editorUtils';

// Monaco Environment setup
if (typeof window !== 'undefined') {
  (window as any).MonacoEnvironment = {
    getWorkerUrl: function (_moduleId: string, _label: string) {
      return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
        self.MonacoEnvironment = {
          baseUrl: '/monaco-editor/esm/'
        };
        self.importScripts = function() {};
        self.require = function() {};
        self.define = function() {};
      `)}`;
    }
  };
}

interface EditorProps {
  value?: string;
  language?: string;
  editable?: boolean;
  actions?: EditorAction[];
  onChange?: (value: string) => void;
  onReady?: (editor: monaco.editor.IStandaloneCodeEditor) => void;
  className?: string;
  style?: React.CSSProperties;
}

export interface EditorRef {
  editor: monaco.editor.IStandaloneCodeEditor | null;
}

const Editor = forwardRef<EditorRef, EditorProps>(({
  value = '',
  language = 'text/plain',
  editable = true,
  actions = [],
  onChange,
  onReady,
  className = '',
  style = { height: '400px', width: '100%' }
}, ref) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const editorRef = useRef<monaco.editor.IStandaloneCodeEditor | null>(null);

  // Expose editor instance to parent
  useImperativeHandle(ref, () => ({
    editor: editorRef.current
  }));

  // Update listener extension function
  const updateListenerExtension = (editor: monaco.editor.IStandaloneCodeEditor) => {
    if (onChange) {
      const currentValue = editor.getValue();
      onChange(currentValue);
    }
  };

  // Initialize Monaco Editor
  useEffect(() => {
    if (!containerRef.current) return;

    const editor = monaco.editor.create(containerRef.current, {
      value,
      language,
      automaticLayout: true,
      readOnly: !editable,
      renderLineHighlight: "none",
      overviewRulerBorder: false,
      minimap: { enabled: false },
      padding: {
        top: 10,
        bottom: 0
      },
      wordWrap: 'on',
      wrappingStrategy: 'advanced',
      scrollBeyondLastLine: false,
      scrollBeyondLastColumn: 0,
      scrollbar: {
        vertical: 'auto',
        horizontal: 'auto',
        verticalScrollbarSize: 10,
        horizontalScrollbarSize: 10
      }
    });

    editorRef.current = editor;

    // Set up content change listener
    editor.getModel()?.onDidChangeContent(() => {
      updateListenerExtension(editor);
    });

    // Add custom actions
    actions.forEach(action => {
      editor.addAction({
        id: action.id,
        label: action.label,
        contextMenuGroupId: action.contextMenuGroupId,
        keybindings: action.keybindings,
        run: () => action.run(editor)
      });
    });

    // Call onReady callback
    if (onReady) {
      onReady(editor);
    }

    // Cleanup function
    return () => {
      editor.dispose();
      editorRef.current = null;
    };
  }, []); // Only run on mount

  // Update value when prop changes
  useEffect(() => {
    if (editorRef.current && value !== editorRef.current.getValue()) {
      editorRef.current.setValue(value);
    }
  }, [value]);

  // Update language when prop changes
  useEffect(() => {
    if (editorRef.current) {
      const model = editorRef.current.getModel();
      if (model) {
        monaco.editor.setModelLanguage(model, language);
      }
    }
  }, [language]);

  // Update readonly state when editable prop changes
  useEffect(() => {
    if (editorRef.current) {
      editorRef.current.updateOptions({ readOnly: !editable });
    }
  }, [editable]);

  // Update actions when they change
  useEffect(() => {
    if (editorRef.current) {
      // Note: Monaco doesn't provide a direct way to remove actions,
      // so we would need to recreate the editor if actions change frequently
      // For now, actions are expected to be stable
    }
  }, [actions]);

  return (
    <div 
      ref={containerRef}
      className={`editor ${!editable ? 'editor-disable' : ''} ${className}`}
      style={style}
    />
  );
});

Editor.displayName = 'Editor';

export default Editor;

// packages/web/src/components/Editor/Editor.vue
<template>
  <div ref="rootRef" class="editor" :class="{
    'editor-disable': !editable
  }" style="height: 400px; width: 100%;"></div>
</template>

<script setup lang="ts">
import {ref, watch, onMounted, onBeforeUnmount, nextTick} from "vue";
import * as monaco from 'monaco-editor';
import type { EditorAction } from '../../utils/editorUtils';

if (typeof window !== 'undefined') {
  (window as any).MonacoEnvironment = {
    getWorkerUrl: function (_moduleId: string, _label: string) {
      return `data:text/javascript;charset=utf-8,${encodeURIComponent(`
        self.MonacoEnvironment = {
          baseUrl: '/monaco-editor/esm/'
        };
        self.importScripts = function() {};
        self.require = function() {};
        self.define = function() {};
      `)}`;
    }
  };
}

const emit = defineEmits(["update:modelValue", "ready"]);
const rootRef = ref<HTMLElement | null>(null);
const props = withDefaults(defineProps<{
  modelValue?: string
  language?: string
  editable?: boolean
  actions?: EditorAction[]
}>(), {
  modelValue: '',
  language: 'text/plain',
  editable: true,
  actions: () => ([])
});

let editor: monaco.editor.IStandaloneCodeEditor | null = null;

onMounted(async () => {
  if (!rootRef.value) return;

  editor = monaco.editor.create(rootRef.value, {
    value: props.modelValue,
    language: props.language,
    automaticLayout: true,
    readOnly: !props.editable,
    renderLineHighlight: "none",
    overviewRulerBorder: false,
    minimap: {enabled: false},
    padding: {
      top: 10
    },
    wordWrap: 'on',
    wrappingStrategy: 'advanced',
  });

  editor.getModel()?.onDidChangeContent(() => {
    updateListenerExtension(editor);
  })

  if (props.actions.length > 0) {
    props.actions.forEach((action) => {
      if (editor) {
        editor.addAction({
          id: action.id,
          label: action.label,
          contextMenuGroupId: action.contextMenuGroupId,
          keybindings: action.keybindings,
          run: (editorInstance) => action.run(editorInstance as monaco.editor.IStandaloneCodeEditor)
        });
      }
    });
  }

  nextTick(() => {
    emit('ready');
  })
});

onBeforeUnmount(() => {
  if (editor) {
    editor.dispose();
  }
});

function updateListenerExtension(editor: monaco.editor.IStandaloneCodeEditor | null) {
  if (!editor) return;
  const value = editor.getValue();
  emit("update:modelValue", value);
}

watch(
  () => props.modelValue,
  (modelValue) => {
    const newValue = modelValue;
    if (editor) {
      const editorValue = editor.getValue();
      if (newValue !== editorValue) {
        editor.setValue(newValue);
      }
    }
  },
  {immediate: true}
);

watch(() => props.language, () => {
  if (!editor) return;
  const model = editor.getModel();
  if (model) {
    monaco.editor.setModelLanguage(model, props.language);
  }
})

defineExpose({editor});
</script>

<style lang="scss">
.editor {
  outline: none;
  overflow: hidden;

  .lines-content.monaco-editor-background {
    padding-left: 5px !important;
  }

  &.editor-disable .monaco-editor-background, &.editor-disable .minimap {
    background-color: #F5F7FA !important;
  }

  .scroll-decoration {
    display: none;
  }
}
</style>
