// packages/web/src/components/ChatBot/EditorViewMode.tsx
import React from 'react';
import { Radio, Button, Modal } from 'antd';
import { DeleteOutlined } from '@ant-design/icons';
import { useBreakpoint } from 'antd';

interface EditorViewModeProps {
  value: string;
  onChange: (value: string) => void;
  onClear: () => void;
}

const EditorViewMode: React.FC<EditorViewModeProps> = ({ value, onChange, onClear }) => {
  const screens = useBreakpoint();
  
  // Show editor preview only on medium screens and larger
  const isShowEditorPreview = screens.md;

  // Auto-switch to editor mode on smaller screens
  React.useEffect(() => {
    if (!isShowEditorPreview && value !== 'editor') {
      onChange('editor');
    }
  }, [isShowEditorPreview, value, onChange]);

  const handleClear = () => {
    Modal.confirm({
      title: 'Confirm!',
      content: 'Are you sure you want to clear the data?',
      onOk: () => {
        onClear();
      },
    });
  };

  const options = [
    { label: 'Editor', value: 'editor' },
    ...(isShowEditorPreview ? [
      { label: 'Preview', value: 'preview' },
      { label: 'Editor + Preview', value: 'editorPreview' }
    ] : [])
  ];

  return (
    <div className="editor-view-mode" style={{ 
      display: 'flex', 
      justifyContent: 'space-between', 
      alignItems: 'center',
      padding: '8px 0',
      borderBottom: '1px solid var(--input-border)',
      marginBottom: '8px'
    }}>
      <Radio.Group
        value={value}
        onChange={(e) => onChange(e.target.value)}
        options={options}
        optionType="button"
        buttonStyle="solid"
        size="small"
      />
      
      <Button
        type="text"
        size="small"
        icon={<DeleteOutlined />}
        onClick={handleClear}
        style={{ color: 'var(--text-secondary)' }}
        title="Clear data"
      />
    </div>
  );
};

export default EditorViewMode;

// packages/ui-backup/src/components/ChatBot/EditorViewMode.vue
<template>
  <div class="editor-view-mode">
    <el-button @click="onClear" class="btn-clear" size="small">
      <TrashSmallIcon/>
      Clear
    </el-button>
    <el-radio-group v-model="mode" size="small">
      <el-radio-button label="Editor" value="editor"/>
      <el-radio-button v-if="isShowEditorPreview" label="Editor and Preview" value="editorPreview"/>
      <el-radio-button label="Preview" value="preview"/>
    </el-radio-group>
  </div>
</template>

<script setup lang="ts">
import {computed, watch} from "vue";
import helperBreakpoints from "@/helpers/HelperBreakpoints";
import TrashSmallIcon from "@/assets/images/icons/trash-small.svg"
import {ElMessageBox} from "element-plus";

const mode = defineModel();
const emit = defineEmits(['clear']);

const isShowEditorPreview = computed(() => {
  return !helperBreakpoints.smaller('md').value;
})

function onClear() {
  ElMessageBox.confirm("Are you sure you want to clear the data?", "Confirm!", {
    callback: async (action) => {
      if (action === "confirm") {
        emit("clear");
      }
    }
  });
}

watch(isShowEditorPreview, () => {
  mode.value = 'editor';
})
</script>

<style lang="scss">
.editor-view-mode {
  text-align: right;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 32px 16px;

  .btn-clear {
    svg {
      margin-right: 5px;
      width: 15px;
    }
  }
}
</style>
