// packages/web/src/components/LoadingText.tsx
import React, { useState, useEffect, useMemo } from 'react';
import { useTranslation } from 'react-i18next';

const LoadingText: React.FC = () => {
  const { t } = useTranslation();
  const [counter, setCounter] = useState(0);

  useEffect(() => {
    const timeIntervalId = setInterval(() => {
      setCounter(prev => (prev >= 3 ? 0 : prev + 1));
    }, 1000);

    return () => {
      clearInterval(timeIntervalId);
    };
  }, []);

  const label = useMemo(() => {
    return `${t('common.loading')} ${'.'.repeat(counter)}`;
  }, [t, counter]);

  return <span>{label}</span>;
};

export default LoadingText;

// packages/web/src/components/LoadingText.vue
<template>
  <span>{{ label }}</span>
</template>

<script setup lang="ts">
import {computed, onBeforeUnmount, onMounted, ref} from "vue";
import {useI18n} from "vue-i18n";
const { t } = useI18n();

const counter = ref(0);
let timeIntervalId = null;

const label = computed(() => {
  return `${t('common.loading')} ${'.'.repeat(counter.value)}`
});

onMounted(init);

function init() {
  timeIntervalId = setInterval(() => {
    counter.value += 1;
    if (counter.value > 3) counter.value = 0;
  }, 1000);
}

onBeforeUnmount(() => {
  if (timeIntervalId) clearInterval(timeIntervalId);
})
</script>

<style scoped lang="scss">

</style>
