// packages/web/src/App.tsx
import React, { useEffect, useState } from 'react';
import { useLocation, useNavigate, Outlet } from 'react-router-dom';
import { useAuth0 } from '@auth0/auth0-react';

// Import stores
import { useAuthStore } from './stores/auth';
import { useAssistantStore } from './stores/assistant';

// Import components
import ErrorBoundary from './components/ErrorBoundary/ErrorBoundary';
import LoginPopUp from './components/LoginPopUp/LoginPopUp';
import ChatBotRenameDialog from './components/ChatBot/ChatBotRenameDialog';
import ConfirmationDialog from './components/ConfirmationDialog/ConfirmationDialog';

// Import helpers
import HelperStorage from './helpers/HelperStorage';
import { LOGIN_REDIRECT_URL } from './helpers/HelperConstants';
import { isInIframe } from './helpers/HelperIframe';
import { setTokenGetter } from './helpers/HelperAuth';
import { useDetectTheme } from './helpers/HelperTheme';
import { useNavigationGuards } from './router';
import { initializeCleanState } from './utils/clearTestData';

const App: React.FC = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const { user, getAccessTokenSilently, isAuthenticated, isLoading: auth0Loading, error: auth0Error } = useAuth0();
  const [firstVisit, setFirstVisit] = useState(true);

  const authStore = useAuthStore();
  const assistantStore = useAssistantStore();
  const detectTheme = useDetectTheme();
  const helperStorage = new HelperStorage();
  const { handleFirstVisit } = useNavigationGuards();

  // Debug Auth0 state changes
  useEffect(() => {

  }, [isAuthenticated, auth0Loading, user, auth0Error]);

  // Set up token getter for API calls
  useEffect(() => {
    setTokenGetter(async () => {
      try {
        return await getAccessTokenSilently();
      } catch (error) {
        console.error('Error getting access token:', error);
        throw error;
      }
    });
  }, [getAccessTokenSilently]);

  // Initialize clean state on app load
  useEffect(() => {
    initializeCleanState();
  }, []);

  // Handle theme changes - always enforce dark mode
  useEffect(() => {
    const root = document.documentElement;
    root.classList.remove('theme-dark', 'theme-light');
    // Always apply dark theme - light mode not supported
    root.classList.add('theme-dark');
  }, []);

  // Handle authentication state changes
  useEffect(() => {
    const currentAuthState = useAuthStore.getState();

    if (!isAuthenticated || (currentAuthState.token && currentAuthState.tokenType === 'private')) return;

    // Set flag immediately if we have an old token to prevent any getChats calls during transition
    const currentState = useAuthStore.getState();
    if (currentState.token) {
      assistantStore.setIsTransferringChats(true);
    }

    const handleAuth = async () => {
      try {
        const oldToken = currentState.token;
        const token = await getAccessTokenSilently();



        // Parse JWT token to extract caas_cyoda_employee
        let isCyodaEmployee = false;
        try {
          const base64Url = token.split('.')[1];
          const base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
          const jsonPayload = decodeURIComponent(
            atob(base64)
              .split('')
              .map(c => '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2))
              .join('')
          );
          const parsed = JSON.parse(jsonPayload);
          isCyodaEmployee = parsed.caas_cyoda_employee === true;

        } catch (e) {
          console.error('❌ Error parsing JWT token:', e);
        }

        const authData = {
          token: token,
          tokenType: "private",
          refreshToken: null,
          userId: user?.sub || '',
          username: user?.name || '',
          picture: user?.picture || '',
          family_name: user?.family_name || '',
          given_name: user?.given_name || '',
          email: user?.email || '',
          isCyodaEmployee: isCyodaEmployee,
          superUserMode: false, // Reset super user mode on login
        };

        useAuthStore.getState().saveData(authData);

        if (oldToken) {
          try {
            await useAuthStore.getState().postTransferChats(oldToken, true);

            // Load chats after transfer with NEW user token
            await assistantStore.getChats();
          } catch (error) {
            console.error('Error transferring chats:', error);
          } finally {
            // Clear the flag
            assistantStore.setIsTransferringChats(false);
          }
        } else {

          // Clear the flag since there's no transfer
          assistantStore.setIsTransferringChats(false);

          // Load chats for new user login
          try {
            await assistantStore.getChats();
          } catch (error) {
            console.error('Error loading chats after login:', error);
          }
        }

        assistantStore.setGuestChatsExist(false);

        const returnTo = helperStorage.get(LOGIN_REDIRECT_URL, '/');
        helperStorage.removeItem(LOGIN_REDIRECT_URL);

        // Navigate to return URL
        navigate(returnTo, { replace: true });
      } catch (error) {
        console.error('Error during authentication:', error);
      }
    };

    handleAuth();
  }, [isAuthenticated, user, getAccessTokenSilently, navigate]);

  // Handle navigation guards on route changes
  useEffect(() => {
    if (firstVisit) {
      const redirectTo = handleFirstVisit(location.pathname, location.search);
      if (redirectTo) {
        navigate(redirectTo.pathname + redirectTo.search, { replace: true });
      }
      setFirstVisit(false);
    }
  }, [location, firstVisit, handleFirstVisit, navigate]);

  return (
    <ErrorBoundary>
      <div className="app">
        <Outlet />

        <LoginPopUp />
        <ChatBotRenameDialog />
        <ConfirmationDialog />
      </div>
    </ErrorBoundary>
  );
};

export default App;

// packages/web/src/App.vue
<template>
  <component v-loading="isLoading" :is="layout">
    <el-alert class="alert" title="Not Live Yet, user beware, here be dragons" type="info" show-icon
              :closable="false"/>
    <RouterView/>
    <LoginPopUp/>
    <ChatBotRenameDialog ref="chatBotRenameDialogRef" />
    <ConfirmationDialog/>
    <!--    <DeveloperComponentIcon v-if="isDev"/>-->
  </component>
</template>

<script setup lang="ts">
import {useRoute, RouterView, useRouter} from "vue-router";
import {computed, onMounted, ref, watch, watchEffect} from "vue";
import LoginPopUp from "@/components/LoginPopUp/LoginPopUp.vue";
import {useAuth0} from "@auth0/auth0-vue";
import useAuthStore from "@/stores/auth";
import HelperStorage from "@/helpers/HelperStorage";
import {LOGIN_REDIRECT_URL} from "@/helpers/HelperConstants";
import {isInIframe} from "@/helpers/HelperIframe";
import useAssistantStore from "@/stores/assistant";
import {setTokenGetter} from "@/helpers/HelperAuth";
import {useDetectTheme} from "@/helpers/HelperTheme";
import ChatBotRenameDialog from "@/components/ChatBot/ChatBotRenameDialog.vue";
import ConfirmationDialog from "@/components/ConfirmationDialog/ConfirmationDialog.vue";

const defaultLayout = "default";

const route = useRoute();
const router = useRouter();
const authStore = useAuthStore();
const assistantStore = useAssistantStore();
const detectTheme = useDetectTheme();

onMounted(() => {
  const {getAccessTokenSilently} = useAuth0()

  setTokenGetter(async () => {
    try {
      return await getAccessTokenSilently({
        cacheMode: 'off'
      });
    } catch (error) {
      console.error('Error getting access token:', error);
      throw error;
    }
  });
})

const {user, getAccessTokenSilently, isAuthenticated} = useAuth0();
const isLoading = ref(false);
const layout = computed(() => {
  return `layout-${route.meta.layout || defaultLayout}`;
});

watchEffect(() => {
  const root = document.documentElement;
  root.classList.remove(`theme-dark`);
  root.classList.remove(`theme-light`);
  if (isInIframe && !authStore.isLoggedIn) {
    root.classList.add('theme-light');
    return;
  }

  root.classList.add(`theme-${detectTheme.value}`);
});

const helperStorage = new HelperStorage();

watch(isAuthenticated, async (value) => {
  if (!value || authStore.isLoggedIn) return;
  isLoading.value = true;
  try {
    const oldToken = authStore.token;
    const token = await getAccessTokenSilently();
    authStore.saveData({
      token: token,
      tokenType: "private",
      refreshToken: null,
      userId: user.value.sub,
      username: user.value.name,
      picture: user.value.picture,
      family_name: user.value.family_name,
      given_name: user.value.given_name,
      email: user.value.email,
    })
    if (oldToken) {
      try {
        await authStore.postTransferChats(oldToken, true);
      } catch {}
    }

    assistantStore.setGuestChatsExist(false);
    const returnTo = helperStorage.get(LOGIN_REDIRECT_URL, '/home');
    helperStorage.removeItem(LOGIN_REDIRECT_URL)
    router.replace(returnTo);
  } finally {
    isLoading.value = false;
  }
}, {immediate: true});

</script>

<style scoped lang="scss">
.alert {
  border-radius: 0;
  display: flex;
  justify-content: center;
  height: 60px;
  font-weight: 600;
  background: var(--bg-sidebar) !important;
  ::v-deep(.el-alert__title){
    font-size: 28px !important;
  }
}
</style>
