// packages/web/src/components/ChatBot/ChatBotSubmitForm.vue
<template>
  <div
    @dragenter.prevent="handleDragEnter"
    @dragleave.prevent="handleDragLeave"
    @drop.prevent="handleDrop"
    @dragover.prevent
    class="chat-bot-submit-form"
    :class="{
      'chat-bot-submit-form__drag-started': isDragging,
      'chat-bot-submit-form__layout_canvas': layout === 'canvas'
    }"
  >
    <div class="chat-bot-submit-form__drag-and-drop">
      <span>Drag & Drop</span>
    </div>
    <el-form :model="form" label-width="auto">
      <div class="chat-bot-submit-form__wrapper">
        <div class="chat-bot-submit-form__input-box">
          <div class="chat-bot-submit-form__input">
            <FileSubmitPreview class="chat-bot-submit-form__file-submit-preview" v-if="currentFile" :file="currentFile"
                               @delete="currentFile=null"/>
            <div class="chat-bot-submit-form__input-inner">
              <el-input
                v-model="form.answer"
                type="textarea"
                resize="none"
                :autosize="{ minRows: 1, maxRows: 10 }"
                :placeholder="placeholderComputed"
                @keydown="handleKeyDown"
              />
              <div class="chat-bot-submit-form__btn-submit">
                <button class="btn btn-primary btn-icon"
                        @click.prevent="onClickTextAnswer">
                  <SendIcon/>
                </button>
              </div>
            </div>
          </div>
        </div>
        <div class="chat-bot-submit-form__actions">
          <el-button @click="onClickAttachFile" class="btn-default btn-icon">
            <AttachIcon/>
            <input
              ref="fileInput"
              type="file"
              style="display: none;"
              @change="handleFileSelect"
              accept=".pdf,.docx,.xlsx,.pptx,.xml,.json,text/*,image/*"
            />
          </el-button>
          <el-button disabled class="btn-default btn-icon">
            <PencilIcon/>
          </el-button>
          <el-button disabled class="btn-default btn-icon">
            <LinkIcon/>
          </el-button>
        </div>
      </div>
    </el-form>
  </div>
</template>

<script lang="ts" setup>
import {computed, ref, useTemplateRef} from "vue";
import SendIcon from '@/assets/images/icons/send.svg';
import LinkIcon from '@/assets/images/icons/link.svg';
import AttachIcon from '@/assets/images/icons/attach.svg';
import PencilIcon from '@/assets/images/icons/pencil.svg';
import FileSubmitPreview from "@/components/FileSubmitPreview/FileSubmitPreview.vue";
import HelperUpload from "@/helpers/HelperUpload";
import {ElMessageBox} from "element-plus";

const props = withDefaults(defineProps<{ layout: 'default' | 'canvas' }>(), {
  layout: 'default'
})

const form = ref({
  answer: ''
});

const currentFile = ref(null);
const fileInput = useTemplateRef('fileInput');
const isDragging = ref(false);

const emit = defineEmits(['answer']);

async function onClickTextAnswer() {
  emit('answer', {
    answer: form.value.answer,
    file: currentFile.value || undefined
  });
  form.value.answer = '';
  currentFile.value = null;
}

function onClickAttachFile() {
  fileInput.value.click();
}

function handleFileSelect(event) {
  const file = event.target.files[0];
  const {isValid, message} = HelperUpload.validateFile(file);
  if (!isValid) {
    ElMessageBox.alert(message, 'Warning!', {
      type: 'warning',
    });
    return;
  }
  if (file) {
    currentFile.value = file;
  }
  event.target.value = '';
}

let dragCounter = 0;

function handleDragEnter() {
  dragCounter++;
  isDragging.value = true;
}

function handleDragLeave() {
  dragCounter--;
  if (dragCounter === 0) isDragging.value = false;
}

function handleDrop(event) {
  dragCounter = 0;
  isDragging.value = false;

  currentFile.value = event.dataTransfer.files[0];
}

const placeholderComputed = computed(() => {
  if (props.layout === 'canvas') return 'Type here';
  return 'Use icons on  the right side or simply type';
});

function handleKeyDown(event) {
  if (event.key === 'Enter' && !event.shiftKey) {
    event.preventDefault();
    onClickTextAnswer();
  }
}

</script>

<style lang="scss">
.chat-bot-submit-form {
  position: relative;

  &__drag-and-drop {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    justify-content: center;
    background-color: #fff;
    color: var(--color-primary);
    align-items: center;
    z-index: 1;
    border: 1px dashed var(--color-primary);
    display: none;
    border-radius: 8px;
  }

  &__drag-started &__drag-and-drop {
    display: flex;
  }

  &__wrapper {
    display: flex;
    align-items: end;
  }

  &__input-box {
    flex: 1;
  }

  &__input {
    border: 1px solid var(--border-color-darken);
    border-radius: 8px;
    flex: 1;
    overflow: hidden;
    background-color: var(--input);
  }

  &__input-inner {
    display: flex;
    margin: 0;
    align-items: end;
    min-height: 54px;
  }

  &__btn-submit {
    margin-right: 16px;
    margin-left: 16px;
    margin-bottom: 7px;

    button {
      cursor: pointer;
      border: none;
      border-radius: 4px;
    }

    svg {
      position: relative;
      top: 2px;
      fill: var(--color-icon-submit) !important;
    }
  }

  &__actions {
    margin-left: 16px;
    display: flex;
    gap: 16px;
    margin-bottom: 8px;

    .el-button {
      margin: 0;
    }
  }

  .el-textarea__inner {
    box-shadow: none !important;
    min-height: 40px !important;
    font-size: 16px;
    margin-bottom: 7px;
    margin-top: 7px;
    padding-bottom: 8px;
    padding-top: 8px;
    padding-left: 20px;
  }

  .el-textarea__inner::placeholder {
    color: #A8ABB2;
    font-size: 16px;
    line-height: 24px;
  }

  &__layout_canvas {
    padding-top: 8px;
  }

  &__layout_canvas &__input-box {
    width: 100%;
    order: 2;
  }

  &__layout_canvas &__wrapper {
    flex-direction: column;
  }

  &__layout_canvas &__actions {
    order: 1;
    margin-bottom: 12px;
  }

  &__layout_canvas &__input {
    border-color: var(--border-color-darken);
    background: var(--input);
  }

  &__layout_canvas &__input-inner {
    background-color: var(--input);
    min-height: 70px !important;

    .el-textarea__inner {
      margin-bottom: 15px;
      margin-top: 15px;
    }
  }

  &__layout_canvas &__btn-submit {
    margin-bottom: 15px;
  }

  &__layout_canvas &__file-submit-preview {
    margin-bottom: 8px;
  }

  &__info {
    text-align: center;
    margin-top: 8px;
  }
}
</style>

// packages/web/src/components/ChatBot/ChatBotSubmitForm.tsx
import React, { useState, useRef } from 'react';
import { Form, Input, Button, message } from 'antd';
import SendIcon from '@/assets/images/icons/send.svg?react';
import AttachIcon from '@/assets/images/icons/attach.svg?react';
import FileSubmitPreview from '@/components/FileSubmitPreview/FileSubmitPreview';
import HelperUpload from '@/helpers/HelperUpload';

const { TextArea } = Input;

interface ChatBotSubmitFormProps {
  layout?: 'default' | 'canvas';
  disabled: boolean;
  onAnswer: (data: { answer: string; file?: File }) => void;
}

const ChatBotSubmitForm: React.FC<ChatBotSubmitFormProps> = ({
  layout = 'default',
  disabled,
  onAnswer
}) => {
  const [form] = Form.useForm();
  const [answer, setAnswer] = useState('');
  const [currentFile, setCurrentFile] = useState<File | null>(null);
  const [isDragging, setIsDragging] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  let dragCounter = 0;

  const onClickTextAnswer = async () => {
    if (!answer.trim() && !currentFile) return;

    onAnswer({
      answer: answer,
      file: currentFile || undefined
    });

    setAnswer('');
    setCurrentFile(null);
    form.resetFields();
  };

  const onClickAttachFile = () => {
    fileInputRef.current?.click();
  };

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const { isValid, message: errorMessage } = HelperUpload.validateFile(file);
    if (!isValid) {
      message.warning(errorMessage);
      return;
    }

    setCurrentFile(file);
    event.target.value = '';
  };

  const handleDragEnter = (event: React.DragEvent) => {
    event.preventDefault();
    dragCounter++;
    setIsDragging(true);
  };

  const handleDragLeave = (event: React.DragEvent) => {
    event.preventDefault();
    dragCounter--;
    if (dragCounter === 0) setIsDragging(false);
  };

  const handleDrop = (event: React.DragEvent) => {
    event.preventDefault();
    dragCounter = 0;
    setIsDragging(false);

    const file = event.dataTransfer.files[0];
    if (file) {
      const { isValid, message: errorMessage } = HelperUpload.validateFile(file);
      if (!isValid) {
        message.warning(errorMessage);
        return;
      }
      setCurrentFile(file);
    }
  };

  const handleKeyDown = (event: React.KeyboardEvent) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      onClickTextAnswer();
    }
  };

  const placeholderText = layout === 'canvas' ? 'Type here' : 'Ask Cyoda AI Assistant...';

  return (
    <div
      onDragEnter={handleDragEnter}
      onDragLeave={handleDragLeave}
      onDrop={handleDrop}
      onDragOver={(e) => e.preventDefault()}
      className={`chat-bot-submit-form ${isDragging ? 'chat-bot-submit-form__drag-started' : ''} ${
        layout === 'canvas' ? 'chat-bot-submit-form__layout_canvas' : ''
      }`}
    >
      <div className="chat-bot-submit-form__drag-and-drop">
        <span>Drag & Drop</span>
      </div>

      <Form form={form} layout="vertical">
        <div className="chat-bot-submit-form__wrapper">
          <div className="chat-bot-submit-form__input-box">
            <div className={`chat-bot-submit-form__input ${disabled ? 'disabled' : ''}`}>
              {currentFile && (
                <FileSubmitPreview
                  className="chat-bot-submit-form__file-submit-preview"
                  file={currentFile}
                  onDelete={() => setCurrentFile(null)}
                />
              )}

              <div className="chat-bot-submit-form__input-inner">
                <TextArea
                  value={answer}
                  onChange={(e) => setAnswer(e.target.value)}
                  placeholder={placeholderText}
                  autoSize={{ minRows: 1, maxRows: 10 }}
                  onKeyDown={handleKeyDown}
                  disabled={disabled}
                  style={{ resize: 'none' }}
                />

                <div className="chat-bot-submit-form__actions">
                  <Button
                    onClick={onClickAttachFile}
                    className="btn-default btn-icon transparent"
                    disabled={disabled}
                    icon={<AttachIcon className="chat-bot-submit-form__attach-icon" />}
                  />

                  <input
                    ref={fileInputRef}
                    type="file"
                    disabled={disabled}
                    style={{ display: 'none' }}
                    onChange={handleFileSelect}
                    accept=".pdf,.docx,.xlsx,.pptx,.xml,.json,text/*,image/*"
                  />

                  <button
                    className="btn btn-primary btn-icon"
                    disabled={disabled || (!answer.trim() && !currentFile)}
                    onClick={onClickTextAnswer}
                    type="button"
                  >
                    <SendIcon />
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Form>
    </div>
  );
};

export default ChatBotSubmitForm;
