// packages/web/src/components/ChatBot/ChatBotMenuMobile.vue
<template>
  <div class="chat-bot-mobile-menu">
    <el-dropdown popperClass="chat-bot-mobile-menu__dropdown" @command="handleCommand">
      <VerticalDotsIcon/>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item command="delete">
            <TrashSmallIcon/>
            Delete Chat
          </el-dropdown-item>
          <el-dropdown-item command="toggleCanvas">
            <ToggleCanvasIcon/>
            {{ toggleCanvasTitle }}
          </el-dropdown-item>
          <el-dropdown-item command="entitiesDetails">
            <EntitiesDataIcon class="icon"/>
            Entities Data
          </el-dropdown-item>
          <el-dropdown-item command="support">
            <SupportIcon/>
            Contact Support
          </el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>
  </div>
</template>

<script setup lang="ts">
import VerticalDotsIcon from "@/assets/images/icons/vertical-dots.svg";
import EntitiesDataIcon from "@/assets/images/icons/entities-data.svg";
import TrashSmallIcon from "@/assets/images/icons/trash-small.svg";
import SupportIcon from '@/assets/images/icons/support.svg';
import ToggleCanvasIcon from "@/assets/images/icons/toggle-canvas.svg";
import {computed, inject} from "vue";

const emit = defineEmits(['delete', 'toggleCanvas', 'entitiesDetails', 'support']);

const handleCommand = (command: string | number | object) => {
  emit(command);
}

const canvasVisible = inject('canvasVisible');

const toggleCanvasTitle = computed(() => {
  return canvasVisible.value ? 'Close Canvas' : 'Open Canvas';
})
</script>

<style lang="scss">
.chat-bot-mobile-menu__dropdown {
  .el-dropdown-menu__item {
    svg {
      margin-right: 12px;
    }
  }
}
</style>

// packages/web/src/components/ChatBot/ChatBotMenuMobile.tsx
import React from 'react';
import { Dropdown, MenuProps } from 'antd';
import { DatabaseOutlined, CustomerServiceOutlined, MoreOutlined } from '@ant-design/icons';
import ToggleCanvasIcon from '@/assets/images/icons/toggle-canvas.svg?react';

interface ChatBotMenuMobileProps {
  canvasVisible?: boolean;
  onToggleCanvas: () => void;
  onEntitiesDetails: () => void;
  onSupport: () => void;
}

const ChatBotMenuMobile: React.FC<ChatBotMenuMobileProps> = ({
  canvasVisible = false,
  onToggleCanvas,
  onEntitiesDetails,
  onSupport
}) => {
  const toggleCanvasTitle = canvasVisible ? 'Close Canvas' : 'Open Canvas';

  const handleMenuClick: MenuProps['onClick'] = ({ key }) => {
    switch (key) {
      case 'toggleCanvas':
        onToggleCanvas();
        break;
      case 'entitiesDetails':
        onEntitiesDetails();
        break;
      case 'support':
        onSupport();
        break;
    }
  };

  const menuItems: MenuProps['items'] = [
    {
      key: 'toggleCanvas',
      icon: <ToggleCanvasIcon />,
      label: toggleCanvasTitle,
    },
    {
      key: 'entitiesDetails',
      icon: <DatabaseOutlined />,
      label: 'Entities Data',
    },
    {
      key: 'support',
      icon: <CustomerServiceOutlined />,
      label: 'Contact Support',
    },
  ];

  return (
    <div className="chat-bot-mobile-menu">
      <Dropdown
        menu={{ items: menuItems, onClick: handleMenuClick }}
        placement="bottomRight"
        trigger={['click']}
      >
        <MoreOutlined className="chat-bot-mobile-menu__icon" />
      </Dropdown>
    </div>
  );
};

export default ChatBotMenuMobile;
