// packages/web/src/components/ChatBot/ChatBotEditorMarkdown.tsx
import React, { useState, useRef, useEffect, useMemo } from 'react';
import { Splitter, Button, Tooltip, Badge, Spin } from 'antd';
import { SendOutlined, PaperClipOutlined } from '@ant-design/icons';
import Editor from '@/components/Editor/Editor';
import EditorViewMode from './EditorViewMode';
import ChatBotAttachFile, { ChatBotAttachFileRef } from './ChatBotAttachFile';
import HelperMarkdown from '@/helpers/HelperMarkdown';
import HelperStorage from '@/helpers/HelperStorage';
import { createMarkdownEditorActions, type EditorAction } from '@/utils/editorUtils';
import { useAssistantStore } from '@/stores/assistant';

interface ChatBotEditorMarkdownProps {
  technicalId: string;
  onAnswer: (data: { answer: string; file?: File }) => void;
}

const ChatBotEditorMarkdown: React.FC<ChatBotEditorMarkdownProps> = ({
  technicalId,
  onAnswer
}) => {
  const [editorActions, setEditorActions] = useState<EditorAction[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [currentFile, setCurrentFile] = useState<File | null>(null);
  const [editorSize, setEditorSize] = useState<number>(50);
  const [editorMode, setEditorMode] = useState('editorPreview');
  const [canvasData, setCanvasData] = useState('');
  
  const assistantStore = useAssistantStore();
  const chatBotAttachFileRef = useRef<ChatBotAttachFileRef>(null);
  const isLoadingRef = useRef(isLoading);
  const currentFileRef = useRef(currentFile);
  const helperStorage = new HelperStorage();

  // Storage keys
  const EDITOR_WIDTH = 'chatBotEditorMarkdown:width';
  const EDITOR_MODE = 'chatBotEditorMarkdown:editorMode';
  const markdownCanvasDataKey = `chatBotEditorMarkdown:canvasData:${technicalId}`;

  // Update refs when state changes
  useEffect(() => {
    isLoadingRef.current = isLoading;
  }, [isLoading]);

  useEffect(() => {
    currentFileRef.current = currentFile;
  }, [currentFile]);

  // Load initial values from storage
  useEffect(() => {
    const savedEditorSize = helperStorage.get(EDITOR_WIDTH, 50);
    const savedEditorMode = helperStorage.get(EDITOR_MODE, 'editorPreview');
    const savedCanvasData = helperStorage.get(markdownCanvasDataKey, '') || '';

    setEditorSize(typeof savedEditorSize === 'string' ? 50 : savedEditorSize);
    setEditorMode(savedEditorMode as string);
    setCanvasData(savedCanvasData.toString());
  }, [technicalId]);

  // Save to storage when values change
  useEffect(() => {
    helperStorage.set(EDITOR_WIDTH, editorSize);
  }, [editorSize]);

  useEffect(() => {
    helperStorage.set(EDITOR_MODE, editorMode);
  }, [editorMode]);

  useEffect(() => {
    helperStorage.set(markdownCanvasDataKey, canvasData);
  }, [canvasData, markdownCanvasDataKey]);

  const questionRequest = async (data: any) => {
    if (data.file) {
      const formData = new FormData();
      formData.append('file', data.file);
      formData.append('question', data.question);
      return assistantStore.postQuestions(technicalId, formData);
    } else {
      return assistantStore.postTextQuestions(technicalId, data);
    }
  };

  // Initialize editor actions
  useEffect(() => {
    const actions = createMarkdownEditorActions({
      isLoading: isLoadingRef,
      currentFile: currentFileRef,
      questionRequest,
      onAnswer: (data) => {
        onAnswer(data);
      }
    });
    setEditorActions(actions);
  }, [onAnswer, technicalId]);

  const onAttachFile = () => {
    chatBotAttachFileRef.current?.openDialog(currentFile);
  };

  const countFiles = currentFile ? 1 : 0;

  const onSubmitQuestion = async () => {
    try {
      setIsLoading(true);

      const dataRequest = {
        question: canvasData
      };

      if (currentFile) {
        (dataRequest as any).file = currentFile;
      }

      const { data } = await questionRequest(dataRequest);
      setCurrentFile(null);
      setCanvasData(prev => prev + `\n/*\n${data.message}\n*/`);
    } finally {
      setIsLoading(false);
    }
  };

  const onFile = (file: File | null) => {
    setCurrentFile(file);
  };

  const onClear = () => {
    setCanvasData('');
  };

  const isShowMarkdown = ['preview', 'editorPreview'].includes(editorMode);
  const isShowEditor = ['editor', 'editorPreview'].includes(editorMode);

  const canvasDataWithMarkdown = useMemo(() => {
    return HelperMarkdown.parseMarkdown(canvasData);
  }, [canvasData]);

  return (
    <Spin spinning={isLoading}>
      <div className="chat-bot-editor-markdown" style={{ minHeight: 'calc(100vh - 137px)', height: 'calc(100% - 137px)' }}>
        <EditorViewMode
          value={editorMode}
          onChange={setEditorMode}
          onClear={onClear}
        />
        
        <Splitter
          onResize={(sizes) => {
            if (sizes && sizes[0]) {
              setEditorSize(sizes[0]);
            }
          }}
        >
          {isShowEditor && (
            <Splitter.Panel size={editorSize} style={{ paddingRight: '15px', position: 'relative' }}>
              <Editor
                value={canvasData}
                onChange={setCanvasData}
                actions={editorActions}
                style={{ minHeight: '100%' }}
                className="chat-bot-editor-markdown__editor-inner"
              />
              <div className="chat-bot-editor-markdown__actions" style={{
                position: 'absolute',
                right: '15px',
                bottom: '20px',
                zIndex: 100,
                display: 'flex',
                justifyContent: 'flex-end',
                alignItems: 'center',
                gap: '12px',
                background: 'var(--bg-new-chat)',
                border: '1px solid var(--input-border)',
                padding: '9px 12px',
                borderRadius: '4px'
              }}>
                <Tooltip title="Send Answer" placement="left">
                  <Button
                    type="text"
                    icon={<SendOutlined />}
                    onClick={onSubmitQuestion}
                    className="btn-white btn-icon"
                  />
                </Tooltip>
                <Tooltip title="Attach File" placement="left">
                  <Badge count={countFiles} color="green" showZero={false}>
                    <Button
                      type="text"
                      icon={<PaperClipOutlined />}
                      onClick={onAttachFile}
                      className="btn-white btn-icon"
                    />
                  </Badge>
                </Tooltip>
              </div>
            </Splitter.Panel>
          )}
          
          {isShowMarkdown && (
            <Splitter.Panel style={{ paddingLeft: '15px' }}>
              <div 
                className="chat-bot-editor-markdown__markdown-inner"
                style={{ height: '100%', overflowY: 'auto' }}
                dangerouslySetInnerHTML={{ __html: canvasDataWithMarkdown }}
              />
            </Splitter.Panel>
          )}
        </Splitter>
        
        <ChatBotAttachFile
          ref={chatBotAttachFileRef}
          onFile={onFile}
        />
      </div>
    </Spin>
  );
};

export default ChatBotEditorMarkdown;

// packages/web/src/components/ChatBot/ChatBotEditorMarkdown.vue
<template>
  <div
      v-loading="isLoading"
      class="chat-bot-editor-markdown"
  >
    <EditorViewMode @clear="onClear" v-model="editorMode"/>
    <el-splitter>
      <el-splitter-panel v-if="isShowEditor" v-model:size="editorSize" class="chat-bot-editor-markdown__editor-wrapper">
        <Editor v-model="canvasData" class="chat-bot-editor-markdown__editor-inner" :actions="editorActions"/>
        <div class="chat-bot-editor-markdown__actions">
          <div class="btn-action btn-block">
            <el-tooltip
                class="box-item"
                effect="dark"
                content="Send Answer"
                placement="left"
                :show-after="1000"
            >
              <el-button @click="onSubmitQuestion" class="btn-white btn-icon">
                <SendIcon/>
              </el-button>
            </el-tooltip>
          </div>
          <div class="btn-action btn-block">
            <el-tooltip
                class="box-item"
                effect="dark"
                content="Attach File"
                placement="left"
                :show-after="1000"
            >
              <el-badge :show-zero="false" :value="countFiles" class="item" color="green">
                <el-button @click="onAttachFile" class="btn-white btn-icon">
                  <AttachIcon/>
                </el-button>
              </el-badge>
            </el-tooltip>
          </div>
        </div>
      </el-splitter-panel>
      <el-splitter-panel v-if="isShowMarkdown" class="chat-bot-editor-markdown__markdown-wrapper">
        <div class="chat-bot-editor-markdown__markdown-inner" v-html="canvasDataWithMarkdown"></div>
      </el-splitter-panel>
    </el-splitter>
    <ChatBotAttachFile
        ref="chatBotAttachFileRef"
        @file="onFile"
    />
  </div>
</template>

<script setup lang="ts">
import Editor from "@/components/Editor/Editor.vue";
import SendIcon from "@/assets/images/icons/send.svg";
import AttachIcon from "@/assets/images/icons/attach.svg";
import {computed, ref, useTemplateRef, watch} from "vue";
import useAssistantStore from "@/stores/assistant.ts";
import ChatBotAttachFile from "@/components/ChatBot/ChatBotAttachFile.vue";
import HelperMarkdown from "@/helpers/HelperMarkdown";
import HelperStorage from "@/helpers/HelperStorage";
import {createMarkdownEditorActions, type EditorAction} from "@/utils/editorUtils";
import EditorViewMode from "@/components/ChatBot/EditorViewMode.vue";

const props = defineProps<{
  technicalId: string,
}>();

const editorActions = ref<EditorAction[]>([]);
const isLoading = ref(false);
const assistantStore = useAssistantStore();
const emit = defineEmits(['answer']);
const chatBotAttachFileRef = useTemplateRef('chatBotAttachFileRef');
const currentFile = ref<File | null>(null);
const helperStorage = new HelperStorage();
const EDITOR_WIDTH = 'chatBotEditorMarkdown:width';
const EDITOR_MODE = 'chatBotEditorMarkdown:editorMode';

const editorSize = ref(helperStorage.get(EDITOR_WIDTH, '50%'));
const editorMode = ref(helperStorage.get(EDITOR_MODE, 'editorPreview'));


const markdownCanvasDataKey = computed(() => `chatBotEditorMarkdown:canvasData:${props.technicalId}`);
const canvasData = ref(helperStorage.get(markdownCanvasDataKey.value, '')?.toString());

const isShowMarkdown = computed(() => {
  return ['preview', 'editorPreview'].includes(editorMode.value);
})

const isShowEditor = computed(() => {
  return ['editor', 'editorPreview'].includes(editorMode.value);
})

initializeEditorActions();

function onAttachFile() {
  chatBotAttachFileRef.value.openDialog(currentFile.value);
}

const countFiles = computed(() => {
  return currentFile.value ? 1 : 0;
})

async function onSubmitQuestion() {
  try {
    isLoading.value = true;

    const dataRequest = {
      question: canvasData.value
    };

    if (currentFile.value) {
      dataRequest.file = currentFile.value;
    }

    const {data} = await questionRequest(dataRequest)
    currentFile.value = null;
    canvasData.value += `\n/*\n${data.message}\n*/`;
  } finally {
    isLoading.value = false;
  }
}

async function questionRequest(data: any) {
  if (data.file) {
    const formData = new FormData();
    formData.append('file', data.file);
    formData.append('question', data.question);

    return assistantStore.postQuestions(props.technicalId, formData);
  } else {
    return assistantStore.postTextQuestions(props.technicalId, data);
  }
}

async function onSubmitAnswer() {
  const dataRequest = {
    answer: canvasData.value
  };

  if (currentFile.value) {
    dataRequest.file = currentFile.value;
  }

  emit('answer', dataRequest);
  currentFile.value = null;
}

function initializeEditorActions() {
  const actions = createMarkdownEditorActions({
    isLoading,
    currentFile,
    questionRequest,
    onAnswer: (data) => {
      emit('answer', data);
    }
  });

  editorActions.value = actions;
}

const canvasDataWithMarkdown = computed(() => {
  return HelperMarkdown.parseMarkdown(canvasData.value);
})

function onFile(file: File) {
  currentFile.value = file;
}

function onClear() {
  canvasData.value = '';
}

watch(editorSize, (value) => {
  helperStorage.set(EDITOR_WIDTH, value);
})

watch(editorMode, (value) => {
  helperStorage.set(EDITOR_MODE, value);
})

watch(canvasData, (value) => {
  helperStorage.set(markdownCanvasDataKey.value.toString(), value);
})
</script>

<style lang="scss">
.chat-bot-editor-markdown {
  position: relative;
  min-height: calc(100vh - 137px);
  height: calc(100% - 137px);

  &__editor-wrapper {
    padding-right: 15px;
    position: relative;
  }

  &__markdown-wrapper {
    padding-left: 15px;
  }

  &__editor-inner {
    min-height: 100%;
  }

  &__actions {
    position: absolute;
    right: 15px;
    bottom: 20px;
    z-index: 100;
    display: flex;
    justify-content: end;
    align-items: center;
    gap: 12px;
    background: var(--bg-new-chat);
    border: 1px solid var(--input-border);
    padding: 9px 12px;
    border-radius: 4px;

    button {
      margin: 0 !important;
    }
  }

  &__markdown-inner p:first-child {
    margin-top: 8px;
  }

  &__markdown-inner {
    height: 100%;
    overflow-y: auto;
  }

  &.el-loading-parent--relative {
    .el-loading-mask {
      top: -15px;
      bottom: -55px;
    }
  }
}
</style>
