// packages/web/src/components/AuthState/AuthState.tsx
import React from 'react';
import LoginButton from '@/components/LoginButton/LoginButton';
import AuthStateAvatar from '@/components/AuthState/AuthStateAvatar';
import { useAuthStore } from '@/stores/auth';

const AuthState: React.FC = () => {
  const authStore = useAuthStore();

  return (
    <div>
      {authStore.isLoggedIn ? (
        <AuthStateAvatar />
      ) : (
        <LoginButton />
      )}
    </div>
  );
};

export default AuthState;

// packages/ui-backup/src/components/AuthState/AuthState.vue
<template>
  <div v-if="isLoggedIn">
    <AuthStateAvatar/>
  </div>
  <div v-else>
    <LoginButton/>
  </div>
</template>

<script setup lang="ts">
import LoginButton from "@/components/LoginButton/LoginButton.vue";

import useAuthStore from "@/stores/auth";
import {computed} from "vue";
import AuthStateAvatar from "@/components/AuthState/AuthStateAvatar.vue";

const authStore = useAuthStore();

const isLoggedIn = computed(() => {
  return authStore.isLoggedIn;
})

</script>

<style scoped lang="scss">
</style>
