// packages/web/src/views/DashboardView.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { Button, Typography } from 'antd';
import { MenuOutlined } from '@ant-design/icons';
import AuthState from '@/components/AuthState/AuthState';
import NewChat from '@/components/NewChat/NewChat';

const { Title } = Typography;

interface CreateChatResponse {
  technical_id: string;
}

const DashboardView: React.FC = () => {
  const { t } = useTranslation();
  const navigate = useNavigate();
  const [drawerSidebarVisible, setDrawerSidebarVisible] = useState(false);

  const onCreated = (data: CreateChatResponse) => {
    navigate(`/chat-bot/view/${data.technical_id}`);
  };

  useEffect(() => {
    const BODY_CLASS_NAME = 'body-dashboard-view';
    document.body.classList.add(BODY_CLASS_NAME);

    return () => {
      document.body.classList.remove(BODY_CLASS_NAME);
    };
  }, []);

  return (
    <div className="dashboard-view">
      <div className="dashboard-view__header">
        <Button
          className="btn btn-default btn-icon hidden-above-md"
          onClick={() => setDrawerSidebarVisible(true)}
          icon={<MenuOutlined />}
        />
        <div className="dashboard-view__header-right">
          <AuthState />
        </div>
      </div>

      <div className="dashboard-view__content">
        <Title level={2}>Dashboard</Title>
        <NewChat onCreated={onCreated} />
      </div>

      {/* DrawerSidebar placeholder */}
      {drawerSidebarVisible && (
        <div>Drawer Sidebar Placeholder</div>
      )}
    </div>
  );
};

export default DashboardView;

// packages/ui-backup/src/views/DashboardView.vue
<template>
  <div class="dashboard-view">
    <div class="dashboard-view__actions">
      <div class="dashboard-view__actions-left-part">
        <el-button @click="onClickDrawerSideBar" class="btn btn-default btn-icon hidden-above-md large">
          <MenuIcon/>
        </el-button>
      </div>
      <div class="dashboard-view__actions-right-part">
        <Support size="large"/>
        <AuthState/>
      </div>
    </div>
    <div class="dashboard-view__body">
      <NewChat @created="onCreated"/>
    </div>
    <DrawerSidebar v-model="drawerSidebarVisible"/>
  </div>
</template>

<script setup lang="ts">
import type {CreateChatResponse} from "@/types/chat";
import {useRouter} from "vue-router";
import NewChat from "@/components/NewChat/NewChat.vue";
import {onBeforeUnmount, onMounted, ref} from "vue";
import AuthState from "@/components/AuthState/AuthState.vue";
import Support from "@/components/Support/Support.vue";
import DrawerSidebar from "@/components/DrawerSidebar/DrawerSidebar.vue";
import MenuIcon from "@/assets/images/icons/menu.svg";

const router = useRouter();
const drawerSidebarVisible = ref(false);

function onCreated(data: CreateChatResponse) {
  router.push(`/chat-bot/view/${data.technical_id}`);
}

const BODY_CLASS_NAME = 'body-dashboard-view';

onMounted(() => {
  document.body.classList.add(BODY_CLASS_NAME);
})

onBeforeUnmount(() => {
  document.body.classList.remove(BODY_CLASS_NAME);
})

function onClickDrawerSideBar() {
  drawerSidebarVisible.value = true;
}
</script>

<style lang="scss">
@use '@/assets/css/particular/breakpoints';

.dashboard-view {
  padding-top: 24px;
  padding-left: 29px;
  padding-right: 29px;
  display: flex;
  flex-direction: column;
  min-height: 100vh;

  &__actions {
    display: flex;
    gap: 12px;
    align-items: center;
    justify-content: space-between;
    margin-bottom: 12px;

    @include breakpoints.respond-max('sm') {
      margin-bottom: 36px;
    }
  }

  &__actions-right-part {
    display: flex;
    gap: 12px;
    align-items: center;
  }

  &__body {
    display: flex;
    flex: 1;
    justify-content: center;
    align-items: center;
  }
}
</style>
